# Generated by Django 3.0.8 on 2020-08-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_application', '0002_hardware'),
    ]

    operations = [
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
