# Generated by Django 3.0.8 on 2020-08-08 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_application', '0003_places'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hardWare',
        ),
        migrations.DeleteModel(
            name='places',
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
