# Generated by Django 3.0.8 on 2020-08-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_application', '0005_branches_resturant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturant',
            name='startCount',
            field=models.IntegerField(blank=True),
        ),
    ]
