# Generated by Django 3.0.8 on 2020-08-14 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_application', '0006_auto_20200808_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipName', models.CharField(max_length=50)),
                ('equipVolt', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(0)])),
                ('equipNo', models.BigIntegerField(null=True)),
                ('equipStatus', models.IntegerField(choices=[('1', 'new'), ('2', 'second-hand')])),
            ],
        ),
        migrations.CreateModel(
            name='Factories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factoryName', models.CharField(max_length=50)),
                ('factorySince', models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(4)])),
                ('factoryAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('factoryManagerFullName', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
